// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EAP_WebAPI.Entities
{
    public partial class EqpAlarm
    {
        public int Id { get; set; }
        public string EqpId { get; set; }
        public string AlarmId { get; set; }
        public string AlarmType { get; set; }
        public string AlarmText { get; set; }
        public DateTime AlarmTime { get; set; }

        public virtual EqpInfo Eqp { get; set; }
    }
}