// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EAP_WebAPI.Entities
{
    public partial class EqpInfo
    {
        public EqpInfo()
        {
            EqpAlarm = new HashSet<EqpAlarm>();
            EqpStatus = new HashSet<EqpStatus>();
            EqpWip = new HashSet<EqpWip>();
        }

        public string EqpId { get; set; }
        public string EqpType { get; set; }

        public virtual ICollection<EqpAlarm> EqpAlarm { get; set; }
        public virtual ICollection<EqpStatus> EqpStatus { get; set; }
        public virtual ICollection<EqpWip> EqpWip { get; set; }
    }
}