// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EAP_WebAPI.Entities
{
    public partial class EqpStatus
    {
        public int Id { get; set; }
        public string EqpId { get; set; }
        public string EqpStatusType { get; set; }
        public DateTime EqpStatusTime { get; set; }

        public virtual EqpInfo Eqp { get; set; }
    }
}