// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EAP_WebAPI.Entities
{
    public partial class EqpWip
    {
        public int Id { get; set; }
        public string EqpId { get; set; }
        public string Lot { get; set; }
        public string WaferId { get; set; }
        public DateTime Time { get; set; }

        public virtual EqpInfo Eqp { get; set; }
    }
}